### ISSUE TITLE
Support for PHP7.0

### ISSUE THREAD

**Issue by beathorst** [bmack/site-importer#1]
Very nice extension,

but is not working with PHP 7.0 because the function Yaml::parseFile ist not available in symfony/yaml in version 3.0. But Version 4.0 is only support for PHP 7.1

Would be nice if it works with PHP 7.0

**Comment by bmack** [comment]
ha. that is shitty. However, Symfony 3.4 contains the `Yaml::parseFile` method.

**Comment by bmack** [comment]
Issue solved for you?

**Comment by sabbelasichon** [comment]
@bmack This issue can be closed. I guess.
